kind: pipeline
name: default

steps:
  - name: linter
    image: golangci/golangci-lint:latest
    environment:
      GOPROXY: https://mirrors.aliyun.com/goproxy/
    commands:
      - golangci-lint run

  - name: build
    image: golang:1.17
    environment:
      GOPROXY: https://mirrors.aliyun.com/goproxy/
    commands:
      - go env
      - go mod tidy
      - go test ./util -v
      - go build -v


  - name: publish
    image: plugins/docker:18
    environment:
      GO111MODULE: on 
      GOPROXY: https://mirrors.aliyun.com/goproxy/  
    settings:
      auto_tag: true
      auto_tag_suffix: latest
      dockerfile: Dockerfile
      repo: tantao700/go2rss
      username: tantao700
      password: docker12345678
    volumes:
    - name: dockerv
      path: /var/run/docker.sock      