kind: pipeline
name: default

steps:
- name: linter
  image: golang:1.7
  environment:
    GOPROXY: https://goproxy.cn/
  commands:
  - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
  - golangci-lint run

- name: test
  image: golang
  environment:
    GO111MODULE: on
    GOPROXY: https://goproxy.cn/
  commands:
  - go test -v
  - go build -v