kind: pipeline
name: default

steps:
- name: linter
  image: golang:1.7
  environment:
    - GO111MODULE=on
    - GOPROXY=https://mirrors.aliyun.com/goproxy/
  commands:
    - go env
    - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
    - golangci-lint run

- name: build
  image: golang:1.7
  environment:
    - GO111MODULE=on
    - GOPROXY=https://mirrors.aliyun.com/goproxy/
  commands:
    - go test -v
    - go build -v


# - name: publish
#   image: plugins/docker:18
#   environment:
#     GO111MODULE: on 
#     GOPROXY: https://mirrors.aliyun.com/goproxy/  
#   settings:
#     auto_tag: true
#     auto_tag_suffix: linux-x86
#     dockerfile: Dockerfile
#     repo: tantao700/go2rss